---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: v1
kind: Namespace
metadata:
  name: qas
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: htx
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
