name: Deploy Minikube DevOps

on: push


jobs:

  IaC:
    runs-on: self-hosted
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Create Namespaces
        if: contains('refs/heads/master', github.ref)
        env:
          DEPLOY_CONFIG_FILES: kubernetes/00-namespaces/namespaces.yml 
        run: |
          kubectl apply -f ${DEPLOY_CONFIG_FILES}

      - name: Helm Config
        if: contains('refs/heads/master', github.ref)
        env:
          DEPLOY_CONFIG_FILES: kubernetes/01-helm/
        run: |
          kubectl apply -k ${DEPLOY_CONFIG_FILES}   